#!/bin/bash
if [ $# -lt 1 ];
then 
	echo "Usage: $0 <log-directory>"
	exit 1
fi

if [ -d $1 ];
then
	file_name="log_archive_"$(date "+%Y%m%d_%H%M%S")".tar.gz"
	echo $file_name
	tar -cvzf "$file_name" $1
else
	echo "This is not a directory."
	exit 1
fi



